# Foundry Configuration File
# Default definitions: https://github.com/gakonst/foundry/blob/b7917fa8491aedda4dd6db53fbb206ea233cd531/config/src/lib.rs#L782
# See more config options at: https://github.com/gakonst/foundry/tree/master/config

[profile.default]
solc_version = "0.8.21"
# auto_detect_solc = true
optimizer = true
optimizer_runs = 1_000
bytecode_hash = "none"
cbor_metadata = false
# evm_version = "istanbul"
PRIVATE_KEY="${DEPLOYER_PRIVATE_KEY}"
RPC_URL="${ALFAJORES_RPC_URL}"

[rpc_endpoints]
celo-alfajores = "${ALFAJORES_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
celo = "${CELO_RPC_URL}"

[etherscan]
celo-alfajores = { key = "blockscout", url = "https://celo-alfajores.blockscout.com/api" }
celo = { key = "${CELOSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
